// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBImAHUSPVIdrfGFJRbJa6AfHJghqHke48',
    appId: '1:131505452988:web:placeholder',
    messagingSenderId: '131505452988',
    projectId: 'fantasyfactory-685ab',
    authDomain: 'fantasyfactory-685ab.firebaseapp.com',
    storageBucket: 'fantasyfactory-685ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBImAHUSPVIdrfGFJRbJa6AfHJghqHke48',
    appId: '1:131505452988:android:371c723598cd6a2ee01db9',
    messagingSenderId: '131505452988',
    projectId: 'fantasyfactory-685ab',
    storageBucket: 'fantasyfactory-685ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRxvk9PersoYQE82OPE-vuVzXKwiwsdc4',
    appId: '1:131505452988:ios:9fd51c2163cc993de01db9',
    messagingSenderId: '131505452988',
    projectId: 'fantasyfactory-685ab',
    storageBucket: 'fantasyfactory-685ab.firebasestorage.app',
    iosBundleId: 'com.codermariusz.tradeFactoryMasters',
  );
}
